#needs a make file but i accidently copied it to hw11 and changed it so here is the one for hw11

build:
	gcc HW11-Evenstad.c HW11-A-Evenstad.c HW11-B-Evenstad.c HW11-C-Evenstad.c -c
	gcc HW11-Evenstad.c HW11-A-Evenstad.o HW11-B-Evenstad.o HW11-C-Evenstad.o -lm -o HW11

clean:
	rm *.o -f
	rm HW11 -f
